// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQpuF6oGFgRzAS4X1Uikp0ss7ig0rKMJY',
    appId: '1:832726763468:web:02bde75c418943a2603f69',
    messagingSenderId: '832726763468',
    projectId: 'app-ac37a',
    authDomain: 'app-ac37a.firebaseapp.com',
    storageBucket: 'app-ac37a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvt2P_FU8td3s5MxdAKgya5xwIOlOJ-EY',
    appId: '1:832726763468:android:5f908021d2b0db31603f69',
    messagingSenderId: '832726763468',
    projectId: 'app-ac37a',
    storageBucket: 'app-ac37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFlQFL6EQiqPL39pNpIqw2WI7iYpoKSwo',
    appId: '1:832726763468:ios:f6d65b8a1010e86b603f69',
    messagingSenderId: '832726763468',
    projectId: 'app-ac37a',
    storageBucket: 'app-ac37a.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFlQFL6EQiqPL39pNpIqw2WI7iYpoKSwo',
    appId: '1:832726763468:ios:f6d65b8a1010e86b603f69',
    messagingSenderId: '832726763468',
    projectId: 'app-ac37a',
    storageBucket: 'app-ac37a.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQpuF6oGFgRzAS4X1Uikp0ss7ig0rKMJY',
    appId: '1:832726763468:web:13f1d94bb6d3e117603f69',
    messagingSenderId: '832726763468',
    projectId: 'app-ac37a',
    authDomain: 'app-ac37a.firebaseapp.com',
    storageBucket: 'app-ac37a.appspot.com',
  );
}
